import { Component, OnInit, computed, signal } from '@angular/core';import { CommonModule } from '@angular/common';import { RouterLink } from '@angular/router';import { AlertController, IonBackButton,IonBadge,IonButton,IonButtons,IonContent,IonHeader,IonIcon,IonItem,IonLabel,IonList,IonReorder,IonReorderGroup,IonSelect,IonSelectOption,IonTitle,IonToolbar,ItemReorderEventDetail } from '@ionic/angular';import { addIcons } from 'ionicons';import { downloadOutline, folderOutline, reorderTwoOutline } from 'ionicons/icons';import { StoragePort } from '../../core/storage/storage.port';import { Account, Subscription, Tag } from '../../core/domain/models';import { reorderedWithSort, sortSubscriptions } from '../../core/domain/list-preferences';import { createFolder } from '../../core/domain/folders';import { ListPreferencesService } from '../../core/services/list-preferences.service';import { OpmlExportService } from '../../core/services/opml-export.service';
@Component({selector:'app-subscriptions',template:`<ion-header><ion-toolbar><ion-buttons slot="start"><ion-back-button defaultHref="/feeds"></ion-back-button></ion-buttons><ion-title>Manage subscriptions</ion-title><ion-buttons slot="end"><ion-button aria-label="New folder" (click)="newFolder()"><ion-icon name="folder-outline"></ion-icon></ion-button><ion-button aria-label="Export OPML" (click)="exportOpml()"><ion-icon name="download-outline"></ion-icon></ion-button><ion-button [attr.aria-label]="reordering() ? 'Done reordering' : 'Reorder feeds'" (click)="reordering.set(!reordering())"><ion-icon name="reorder-two-outline"></ion-icon></ion-button><ion-button routerLink="/subscribe">Add</ion-button></ion-buttons></ion-toolbar></ion-header><ion-content><ion-list inset><ion-reorder-group [disabled]="!reordering()" (ionItemReorder)="handleReorder($event)"><ion-item *ngFor="let sub of sorted(); trackBy: track"><ion-label><h2>{{sub.title}}</h2><p>{{sub.feedUrl || sub.htmlUrl}}</p></ion-label><ion-select slot="end" interface="action-sheet" placeholder="No folder" [value]="sub.folderId ?? ''" (ionChange)="setFolder(sub, $event.detail.value)" *ngIf="!reordering()"><ion-select-option value="">No folder</ion-select-option><ion-select-option *ngFor="let folder of folders()" [value]="folder.id">{{folder.label}}</ion-select-option></ion-select><ion-badge slot="end">{{sub.unreadCount}}</ion-badge><ion-reorder slot="end"></ion-reorder></ion-item></ion-reorder-group></ion-list></ion-content>`,imports:[CommonModule,RouterLink,IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonButton,IonIcon,IonContent,IonList,IonItem,IonLabel,IonBadge,IonSelect,IonSelectOption,IonReorder,IonReorderGroup]})
export class SubscriptionsPage implements OnInit{
  account=signal<Account|undefined>(undefined);subscriptions=signal<Subscription[]>([]);folders=signal<Tag[]>([]);reordering=signal(false);
  sorted=computed(()=>this.reordering()?sortSubscriptions(this.subscriptions(),'custom'):sortSubscriptions(this.subscriptions(),this.prefs.feedSort()));
  constructor(private db:StoragePort,public prefs:ListPreferencesService,private opml:OpmlExportService,private alerts:AlertController){addIcons({reorderTwoOutline,downloadOutline,folderOutline});}
  async ngOnInit(){await this.prefs.init();const a=(await this.db.listAccounts())[0];this.account.set(a);if(a){await this.load(a.id);}}
  private async load(accountId:string){const [subs,tags]=await Promise.all([this.db.listSubscriptions(accountId),this.db.listTags(accountId)]);this.subscriptions.set(subs);this.folders.set(tags.filter(t=>t.type==='folder'));}
  async newFolder(){
    const account=this.account();if(!account)return;
    const alert=await this.alerts.create({header:'New folder',inputs:[{name:'label',type:'text',placeholder:'Folder name'}],buttons:[{text:'Cancel',role:'cancel'},{text:'Create',handler:async data=>{const label=(data.label??'').trim();if(!label)return;const folders=this.folders();await this.db.putTags([createFolder(account.id,label,folders.length)]);await this.load(account.id);}}]});
    await alert.present();
  }
  async setFolder(sub:Subscription,folderId:string){const account=this.account();if(!account)return;const next=this.subscriptions().map(s=>s.id===sub.id?{...s,folderId:folderId||undefined}:s);this.subscriptions.set(next);await this.db.putSubscriptions(next.filter(s=>s.id===sub.id));}
  async exportOpml(){await this.opml.export(sortSubscriptions(this.subscriptions(),'custom'));}
  async handleReorder(event:CustomEvent<ItemReorderEventDetail>){
    const next=reorderedWithSort(this.subscriptions(),event.detail.from,event.detail.to);
    this.subscriptions.set(next);
    await Promise.all([this.db.putSubscriptions(next),this.prefs.setFeedSort('custom')]);
    event.detail.complete();
  }
  track(_:number,x:{id:string}){return x.id;}
}
