import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { Router } from '@angular/router';
import { IonAccordion,IonAccordionGroup,IonBackButton,IonButton,IonButtons,IonContent,IonHeader,IonInput,IonItem,IonLabel,IonList,IonSearchbar,IonSegment,IonSegmentButton,IonSpinner,IonTitle,IonToolbar, ToastController } from '@ionic/angular';
import { StoragePort } from '../../core/storage/storage.port'; import { LocalFeedService } from '../../core/services/local-feed.service'; import { DirectoryBundle,DirectoryFeed,DirectoryService,PodcastResult } from '../../core/services/directory.service';
@Component({selector:'app-subscribe',templateUrl:'subscribe.page.html',styleUrls:['subscribe.page.scss'],imports:[CommonModule,FormsModule,IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonContent,IonSegment,IonSegmentButton,IonList,IonItem,IonInput,IonLabel,IonButton,IonSpinner,IonSearchbar,IonAccordion,IonAccordionGroup]})
export class SubscribePage implements OnInit { mode:'url'|'browse'|'news'|'podcasts'|'opml'='url';url='';query='';busy=signal(false);pending=signal('');accountId='';bundles=signal<DirectoryBundle[]>([]);podcasts=signal<PodcastResult[]>([]);keywords=signal<string[]>([]);filtered=signal<DirectoryBundle[]>([]);
constructor(private db:StoragePort,private feeds:LocalFeedService,private directory:DirectoryService,private router:Router,private toasts:ToastController){} async ngOnInit(){const accounts=await this.db.listAccounts();if(!accounts.length){await this.router.navigateByUrl('/accounts');return;}this.accountId=accounts[0].id;await this.loadDirectory();}
async switchMode(mode:typeof this.mode){this.mode=mode;this.query='';this.podcasts.set([]);if(mode==='browse'||mode==='news')await this.loadDirectory();if(mode==='podcasts'&&!this.keywords().length)this.keywords.set(await this.directory.podcastKeywords());}
async loadDirectory(){if(this.mode!=='browse'&&this.mode!=='news')return;this.busy.set(true);try{const rows=await this.directory.bundles(this.mode);this.bundles.set(rows);this.filtered.set(rows);}catch(e){await this.fail(e);}finally{this.busy.set(false);}}
filterDirectory(value:string){this.query=value;const q=value.toLowerCase();this.filtered.set(this.bundles().filter(b=>b.title.toLowerCase().includes(q)||b.feeds.some(f=>f.title.toLowerCase().includes(q))));}
async searchPodcast(value=this.query){if(!value.trim())return;this.query=value;this.busy.set(true);try{this.podcasts.set(await this.directory.searchPodcasts(value));}catch(e){await this.fail(e);}finally{this.busy.set(false);}}
async add(value:string|DirectoryFeed){const url=typeof value==='string'?value:value.url;if(!url)return;this.busy.set(true);this.pending.set(url);try{const sub=await this.feeds.subscribe(this.accountId,url);this.url='';await this.toast(sub.unreadCount>0?`Added ${sub.title} - ${sub.unreadCount} new article${sub.unreadCount===1?'':'s'}`:`Added ${sub.title} (no articles in this feed yet)`,'success');}catch(e){await this.fail(e);}finally{this.busy.set(false);this.pending.set('');}}
async opml(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;this.busy.set(true);try{const r=await this.feeds.importOpml(this.accountId,await file.text());await this.toast(r.failed.length?`Imported ${r.imported} feed${r.imported===1?'':'s'}; ${r.failed.length} failed`:`Imported ${r.imported} feed${r.imported===1?'':'s'}`,r.failed.length?'warning':'success');if(r.failed.length)await this.toast(`Failed: ${r.failed.slice(0,3).join(', ')}${r.failed.length>3?', ...':''}`,'danger',5000);}catch(e){await this.fail(e);}finally{this.busy.set(false);input.value='';}}
private async toast(message:string,color?:string,duration=3500){const toast=await this.toasts.create({message,duration,position:'bottom',color});await toast.present();}
private async fail(e:unknown){await this.toast(e instanceof Error?e.message:String(e),'danger');}}
