import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { Router } from '@angular/router';
import { IonAccordion,IonAccordionGroup,IonBackButton,IonButton,IonButtons,IonContent,IonHeader,IonInput,IonItem,IonLabel,IonList,IonNote,IonSearchbar,IonSegment,IonSegmentButton,IonSpinner,IonTitle,IonToolbar } from '@ionic/angular';
import { StoragePort } from '../../core/storage/storage.port'; import { LocalFeedService } from '../../core/services/local-feed.service'; import { DirectoryBundle,DirectoryFeed,DirectoryService,PodcastResult } from '../../core/services/directory.service';
@Component({selector:'app-subscribe',templateUrl:'subscribe.page.html',styleUrls:['subscribe.page.scss'],imports:[CommonModule,FormsModule,IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonContent,IonSegment,IonSegmentButton,IonList,IonItem,IonInput,IonLabel,IonButton,IonNote,IonSpinner,IonSearchbar,IonAccordion,IonAccordionGroup]})
export class SubscribePage implements OnInit { mode:'url'|'browse'|'news'|'podcasts'|'opml'='url';url='';query='';busy=signal(false);message=signal('');error=signal('');accountId='';bundles=signal<DirectoryBundle[]>([]);podcasts=signal<PodcastResult[]>([]);keywords=signal<string[]>([]);filtered=signal<DirectoryBundle[]>([]);
constructor(private db:StoragePort,private feeds:LocalFeedService,private directory:DirectoryService,private router:Router){} async ngOnInit(){const accounts=await this.db.listAccounts();if(!accounts.length){await this.router.navigateByUrl('/accounts');return;}this.accountId=accounts[0].id;await this.loadDirectory();}
async switchMode(mode:typeof this.mode){this.mode=mode;this.query='';this.podcasts.set([]);if(mode==='browse'||mode==='news')await this.loadDirectory();if(mode==='podcasts'&&!this.keywords().length)this.keywords.set(await this.directory.podcastKeywords());}
async loadDirectory(){if(this.mode!=='browse'&&this.mode!=='news')return;this.busy.set(true);try{const rows=await this.directory.bundles(this.mode);this.bundles.set(rows);this.filtered.set(rows);}catch(e){this.fail(e);}finally{this.busy.set(false);}}
filterDirectory(value:string){this.query=value;const q=value.toLowerCase();this.filtered.set(this.bundles().filter(b=>b.title.toLowerCase().includes(q)||b.feeds.some(f=>f.title.toLowerCase().includes(q))));}
async searchPodcast(value=this.query){if(!value.trim())return;this.query=value;this.busy.set(true);this.error.set('');try{this.podcasts.set(await this.directory.searchPodcasts(value));}catch(e){this.fail(e);}finally{this.busy.set(false);}}
async add(value:string|DirectoryFeed){const url=typeof value==='string'?value:value.url;if(!url)return;this.busy.set(true);this.error.set('');this.message.set('');try{const sub=await this.feeds.subscribe(this.accountId,url);this.message.set(`Added ${sub.title}`);this.url='';}catch(e){this.fail(e);}finally{this.busy.set(false);}}
async opml(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;this.busy.set(true);try{const r=await this.feeds.importOpml(this.accountId,await file.text());this.message.set(`Imported ${r.imported} feeds${r.failed.length?`; ${r.failed.length} failed`:''}.`);}catch(e){this.fail(e);}finally{this.busy.set(false);}} private fail(e:unknown){this.error.set(e instanceof Error?e.message:String(e));}}
